import AppFooter from "@/components/layout/footer";
import AppHeader from "@/components/layout/header";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col items-center gap-4`}
      >
        <Providers>
          <AppHeader />
          <main className="min-h-[100dvh] flex flex-col items-center w-full">
            {children}
          </main>
          <AppFooter />
        </Providers>
      </body>
    </html>
  );
}
